[package]
name = "libcamera-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
libcamera-sys = { path = "../libcamera-sys" }
thiserror = "1.0"
smallvec = "1.10"
num_enum = "0.5"
libc = "0.2"
