[package]
name = "libcamera-sys"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
# libcamera comments are interpreted as rust code blocks failing the doctest
doctest = false

[dependencies]

[build-dependencies]
bindgen = "0.59"
pkg-config = "0.3.26"
cc = "1.0"
